version: '3'
services:
   ccs-ui:
      container_name: ccsui
      image: shrikanthhandadi/ccs-ui
      ports:
      - 3000:80
      restart: on-failure
      links:
      - ccs:ccs
      depends_on:
      - ccs
   ccs:
      container_name: ccs
      image: shrikanthhandadi/ccs
      ports:
      - 9090:9090
      restart: on-failure
      links:
      - mysql:mysql
      depends_on:
      - mysql
   mysql:
      container_name: mysql
      image: mysql/mysql-server:5.7
      ports:
      - 33306:3306
      environment:
         MYSQL_ROOT_PASSWORD: root123
         MYSQL_DATABASE: ccs
         MYSQL_USER: cmad
         MYSQL_PASSWORD: cmad
      volumes:
      - ccs-data:/var/lib/mysql
volumes:
   ccs-data: 