apiVersion: v1
kind: Service
metadata:
   name: ccsui
   labels:
      app: ccsui
spec:
   ports:
   -  port: 80
   selector:
      app: ccsui
      tier: frontend
   type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: ccsui
   labels:
      app: ccsui
spec:
   selector:
      matchLabels:
         app: ccsui
         tier: frontend
   replicas: 1
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: ccsui
            tier: frontend
      spec:
         containers:
         -  image: shrikanthhandadi/ccs-ui:k8
            name: ccsui
            env:
            -  name: SPRING_PROFILES_ACTIVE
               value: prod
            ports:
            -  containerPort: 80
               name: ccsui