apiVersion: v1
kind: Service
metadata:
   name: mongodb
   labels:
      app: ccs
spec:
   ports:
   -  port: 27017
   selector:
      app: ccs
      tier: mongodb
   clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: mongodb
   labels:
      app: ccs
spec:
   selector:
      matchLabels:
         app: ccs
         tier: mongodb
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: ccs
            tier: mongodb
      spec:
         containers:
         -  image: shrikanthhandadi/mongo:4.1
            name: mongodb
            env:
            -  name: MONGO_INITDB_ROOT_USERNAME
               value: root
            -  name: MONGO_INITDB_ROOT_PASSWORD
               value: root123
            -  name: MONGO_INITDB_DATABASE
               value: admin
            ports:
            -  containerPort: 27017
               name: mongodb