apiVersion: v1
kind: Service
metadata:
   name: mysql
   labels:
      app: ccs
spec:
   ports:
   -  port: 3306
   selector:
      app: ccs
      tier: mysql
   clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
   name: mysql
   labels:
      app: ccs
spec:
   selector:
      matchLabels:
         app: ccs
         tier: mysql
   strategy:
      type: Recreate
   template:
      metadata:
         labels:
            app: ccs
            tier: mysql
      spec:
         containers:
         -  image: mysql/mysql-server:5.7
            name: mysql
            env:
            -  name: MYSQL_ROOT_PASSWORD
               value: root123
            -  name: MYSQL_DATABASE
               value: ccs
            -  name: MYSQL_USER
               value: cmad
            -  name: MYSQL_PASSWORD
               value: cmad
            ports:
            -  containerPort: 3306
               name: mysql