version: 0.2
 
phases:  
  install:  
    runtime-versions: 
       java: openjdk11 
  pre_build:  
    commands:
      - pwd
      - cd connected-car-service
      - chmod 777 gradlew 
      - which gradle
  build: 
    commands: 
      - echo Build started on `date` 
      - ./gradlew clean bootWar
  post_build: 
    commands: 
      - echo Build completed on `date` 
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy 
      - ls build
      - mkdir apps
      - cd apps
      - pwd
      - cp ../build/libs/connected-car-service.war ccs.war 
      - cp ../appspec.yml .
      - tar -zcvf ../build/ccs.war.gz *.* 
artifacts: 
  files: 
# IMPORTANT 
# You have to use the tar.gz if you are manually executing CodeDeploy 
#    - target/HelloWorld.tar.gz 
# Use the individual files if you are using the CodeDeploy from CodePipeline 
# Reason is pipeline does not untar and errors out saying that the appspec file is not there 
    - apps/appspec.yml 
    - apps/ccs.war
  discard-paths: yes 
