version: 0.2
 
phases:
  install:
    runtime-versions:
      java: openjdk11
  pre_build:
    commands:
      - echo Just listing basic information about the environment
      - pwd
      - which gradle
      - cd connected-car-service
      - chmod 777 gradlew
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean bootWar
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy
      - mkdir appfiles
      - cd appfiles
      - pwd
      - cp ../build/libs/connected-car-service.war ccs.war
      - cp ../appspec.yml .
      - ls -altr
      - tar -zcvf ../build/ccs.tar.gz *.*
      - cd ..
      - pwd
      - ls -ltr build
artifacts:
  files:
# IMPORTANT
# You have to use the tar.gz if you are manually executing CodeDeploy
    - connected-car-service/build/ccs.tar.gz
# Use the individual files if you are using the CodeDeploy from CodePipeline
# Reason is pipeline does not untar and errors out saying that the appspec file is not there
#    - appfiles/appspec.yml
#    - appfiles/ccs.war
  discard-paths: yes