version: '3'
services:
   ccs:
      image: shrikanthhandadi/ccs
      ports:
      - 2020:2020
      restart: on-failure
      links:
      - mysql:mysql
      depends_on:
      - mysql
   mysql:
      image: mysql/mysql-server:5.7
      ports:
      - 3306
      environment:
         MYSQL_ROOT_PASSWORD: root123
         MYSQL_DATABASE: ccs
         MYSQL_USER: cmad
         MYSQL_PASSWORD: cmad
      volumes:
      - ccs-data:/var/lib/mysql
volumes:
   ccs-data: 