version: '3'
services:
   ccs:
      image: shrikanthhandadi/ccs
      ports:
      - 9090:9090
      depends_on:
      - mysql
   mysql:
      image: mysql/mysql-server:5.7
      ports:
      - 3306:3306
      environment:
         MYSQL_ROOT_PASSWORD: root123
         MYSQL_DATABASE: ccs
         MYSQL_USER: cmad
         MYSQL_PASSWORD: cmad
